version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: posttest
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./posttest_init.sql:/docker-entrypoint-initdb.d/posttest_init.sql
    ports:
      - "5432:5432"

volumes:
  pgdata: