name: Automate Workflow
on:
  push:
    branches: [ main ]

jobs:
  # ==============
  # CI task
  # ==============
  linter:
    name: Run Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Java17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Run Linter
        run: ./gradlew spotlessCheck

  unit-test:
    name: Run Unit Test
    runs-on: ubuntu-latest
    needs:
      - linter
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Java17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Run Unit test
        run: ./gradlew test